# Generated by Django 4.2.1 on 2023-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_vote_preference_score'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('restaurant', 'created'), name='unique_everyday_menu_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('employee', 'preference_score', 'created'), name='unique_preference_score_per_employee'),
        ),
    ]
