# Generated by Django 4.2.1 on 2023-05-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_menu_unique_everyday_menu_per_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menu',
            name='unique_everyday_menu_per_restaurant',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_preference_score_per_employee',
        ),

    ]
